FROM node:18-alpine AS build-stage

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

CMD ["npm" "start"]

FROM  nginx:stable-alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 3000


